running:
  covariance: default
  score_threshold: 0.01
  max_age_since_update: 2
  min_hits_to_birth: 1
  match_type: bipartite
  asso: iou
  has_velo: false
  motion_model: kf
  asso_thres:
    giou: 1.5
    iou: 0.9

redundancy:
  mode: default
  det_score_threshold: 
    iou: 0.01
    giou: 0.01
    m_dis: 0.01
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5

data_loader:
  pc: false